-
  name: Deploy website with ansible
  hosts: ubuntu_groups
  # hosts: ubuntu1
  strategy: free
  # serial: 1
  tasks:
    - name: Install dependency
      apt:
        name: "{{ item }}"
        # state: absent
        state: present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    
    - import_tasks: tasks/deploy_db.yml

    - import_tasks: tasks/deploy_web.yml