- name: Copy deploy_web_script.py to target machine
  copy: src=./scripts/deploy_web_script.py dest=/opt/deploy_web_script.py

- name: Run dummy deploy WEB scripts
  shell: python /opt/deploy_web_script.py
  async: 360
  poll: 0
  register: deploy_web_result

- name: debug deploy_web_result
  debug: 
    msg: "{{deploy_web_result}}"
    
- name: Check deploy web deploy web result
  async_status: jid={{deploy_web_result.ansible_job_id}}
  register: job_result
  until: job_result.finished
  retries: 30