- name: Copy deploy_web_script.py to target machine
  copy: src=./scripts/deploy_web_script.py dest=/opt/deploy_web_script.py

# 12*2=24s
- name: Run dummy deploy WEB scripts
  shell: python /opt/deploy_web_script.py
  async: 360
  poll: 0
  register: deploy_web_result

# 6*2=12s
- name: debug deploy_web_result
  debug: 
    msg: "{{deploy_web_result}}"
    
- name: Copy deploy_db_scripts.py to target machine
  copy: src=./scripts/deploy_db_scripts.py dest=/opt/deploy_db_scripts.py

- name: Run dummy deploy DB scripts
  shell: python /opt/deploy_db_scripts.py
  async: 360
  poll: 0
  register: deploy_db_result

- name: debug deploy_db_result
  debug: 
    msg: "{{deploy_db_result}}"
    

- name: Check deploy db deploy web result
  async_status: jid={{deploy_db_result.ansible_job_id}}
  register: job_result
  until: job_result.finished
  retries: 30

- name: Check deploy web deploy web result
  async_status: jid={{deploy_web_result.ansible_job_id}}
  register: job_result
  until: job_result.finished
  retries: 30


